/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nmpc_func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = 
  {6, 1, 0, 6, 0, 1, 2, 3,
  4, 5};
static const casadi_int casadi_s1[12] = 
  {8, 1, 0, 8, 0, 1, 2, 3,
  4, 5, 6, 7};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[33] = 
  {1, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0};
static const casadi_int casadi_s5[33] = 
  {15, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14};
static const casadi_int casadi_s6[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[38] = 
  {6, 15, 0, 2, 4, 6, 8, 9,
  10, 11, 12, 13, 14, 15, 16, 17,
  18, 20, 0, 2, 1, 3, 2, 4,
  3, 5, 4, 5, 2, 3, 2, 3,
  4, 5, 4, 5, 0, 1};
static const casadi_int casadi_s8[13] = 
  {9, 1, 0, 9, 0, 1, 2, 3,
  4, 5, 6, 7, 8};
static const casadi_int casadi_s9[27] = 
  {9, 15, 0, 0, 0, 0, 0, 0,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 1, 2, 3, 4, 5, 6,
  7, 8, 0};

/* J_v_func:(i0[6],i1[8],i2,i3[6],i4[8],i5,i6,i7,i8[3])->(o0[1x15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0]? arg[0][1] : 0;
  a0=arg[3]? arg[3][1] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[3]? arg[3][2] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[3]? arg[3][3] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[0]? arg[0][4] : 0;
  a0=arg[3]? arg[3][4] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[0]? arg[0][5] : 0;
  a2=arg[3]? arg[3][5] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[4]? arg[4][0] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][6]=a2;
  a2=arg[1]? arg[1][1] : 0;
  a0=arg[4]? arg[4][1] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[1]? arg[1][2] : 0;
  a2=arg[4]? arg[4][2] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a1=arg[4]? arg[4][3] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][9]=a2;
  a2=arg[1]? arg[1][4] : 0;
  a0=arg[4]? arg[4][4] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][10]=a1;
  a1=arg[1]? arg[1][5] : 0;
  a2=arg[4]? arg[4][5] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a1=arg[4]? arg[4][6] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][12]=a2;
  a2=arg[1]? arg[1][7] : 0;
  a0=arg[4]? arg[4][7] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][13]=a1;
  a1=arg[2]? arg[2][0] : 0;
  a2=arg[5]? arg[5][0] : 0;
  a0=arg[8]? arg[8][0] : 0;
  a3=arg[7]? arg[7][0] : 0;
  a4=(a0-a3);
  a5=arg[6]? arg[6][0] : 0;
  a4=(a4/a5);
  a4=exp(a4);
  a4=(a2-a4);
  a4=(a1*a4);
  a0=(a0-a3);
  a0=(a0/a5);
  a0=exp(a0);
  a2=(a2-a0);
  a1=(a1*a2);
  a4=(a4+a1);
  if (res[0]!=0) res[0][14]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int J_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int J_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int J_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void J_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void J_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int J_v_func_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int J_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real J_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s1;
    case 5: return casadi_s2;
    case 6: return casadi_s2;
    case 7: return casadi_s2;
    case 8: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int J_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* J_vv_func:(i0[6],i1[8],i2,i3[6],i4[8],i5,i6,i7,i8[3])->(o0[15x15,15nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][4] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[2]? arg[2][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][14]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_vv_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int J_vv_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int J_vv_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_vv_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int J_vv_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_vv_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void J_vv_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void J_vv_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int J_vv_func_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int J_vv_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real J_vv_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_vv_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_vv_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_vv_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s1;
    case 5: return casadi_s2;
    case 6: return casadi_s2;
    case 7: return casadi_s2;
    case 8: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_vv_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int J_vv_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_vv_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* ceq1_func:(i0[2],i1[6],i2[8],i3,i4,i5,i6[3])->(o0[6]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[3]? arg[3][0] : 0;
  a02=arg[0]? arg[0][0] : 0;
  a02=(a01*a02);
  a02=(a00-a02);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[1]? arg[1][1] : 0;
  a03=arg[0]? arg[0][1] : 0;
  a01=(a01*a03);
  a01=(a02-a01);
  if (res[0]!=0) res[0][1]=a01;
  a01=arg[1]? arg[1][2] : 0;
  a03=arg[2]? arg[2][0] : 0;
  a04=arg[4]? arg[4][0] : 0;
  a05=arg[6]? arg[6][1] : 0;
  a06=(a04/a05);
  a07=arg[2]? arg[2][2] : 0;
  a08=(a03-a07);
  a06=(a06*a08);
  a06=(a03+a06);
  a08=(a05/a04);
  a08=exp(a08);
  a09=(a04/a05);
  a03=(a03-a07);
  a09=(a09*a03);
  a07=(a07+a09);
  a00=(a00-a07);
  a08=(a08*a00);
  a06=(a06+a08);
  a06=(a01-a06);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[1]? arg[1][3] : 0;
  a08=arg[2]? arg[2][1] : 0;
  a00=(a04/a05);
  a07=arg[2]? arg[2][3] : 0;
  a09=(a08-a07);
  a00=(a00*a09);
  a00=(a08+a00);
  a09=(a05/a04);
  a09=exp(a09);
  a05=(a04/a05);
  a08=(a08-a07);
  a05=(a05*a08);
  a07=(a07+a05);
  a02=(a02-a07);
  a09=(a09*a02);
  a00=(a00+a09);
  a00=(a06-a00);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a09=arg[2]? arg[2][4] : 0;
  a02=arg[6]? arg[6][2] : 0;
  a07=(a04/a02);
  a05=arg[2]? arg[2][6] : 0;
  a08=(a09-a05);
  a07=(a07*a08);
  a07=(a09+a07);
  a08=(a02/a04);
  a08=exp(a08);
  a03=(a04/a02);
  a09=(a09-a05);
  a03=(a03*a09);
  a05=(a05+a03);
  a01=(a01-a05);
  a08=(a08*a01);
  a07=(a07+a08);
  a00=(a00-a07);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a07=arg[2]? arg[2][5] : 0;
  a08=(a04/a02);
  a01=arg[2]? arg[2][7] : 0;
  a05=(a07-a01);
  a08=(a08*a05);
  a08=(a07+a08);
  a05=(a02/a04);
  a05=exp(a05);
  a04=(a04/a02);
  a07=(a07-a01);
  a04=(a04*a07);
  a01=(a01+a04);
  a06=(a06-a01);
  a05=(a05*a06);
  a08=(a08+a05);
  a00=(a00-a08);
  if (res[0]!=0) res[0][5]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ceq1_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ceq1_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ceq1_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void ceq1_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ceq1_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int ceq1_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ceq1_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    case 6: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ceq1_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* ceq1_v_func:(i0[2],i1[6],i2[8],i3,i4,i5,i6[3])->(o0[6x15,20nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12;
  a00=1.;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[6]? arg[6][1] : 0;
  a02=arg[4]? arg[4][0] : 0;
  a03=(a01/a02);
  a03=exp(a03);
  a04=(-a03);
  if (res[0]!=0) res[0][1]=a04;
  if (res[0]!=0) res[0][2]=a00;
  a04=(a01/a02);
  a04=exp(a04);
  a05=(-a04);
  if (res[0]!=0) res[0][3]=a05;
  if (res[0]!=0) res[0][4]=a00;
  a05=arg[6]? arg[6][2] : 0;
  a06=(a05/a02);
  a06=exp(a06);
  a07=(-a06);
  if (res[0]!=0) res[0][5]=a07;
  if (res[0]!=0) res[0][6]=a00;
  a07=(a05/a02);
  a07=exp(a07);
  a08=(-a07);
  if (res[0]!=0) res[0][7]=a08;
  if (res[0]!=0) res[0][8]=a00;
  if (res[0]!=0) res[0][9]=a00;
  a08=(a02/a01);
  a09=(a00+a08);
  a10=(a02/a01);
  a11=(a03*a10);
  a09=(a09-a11);
  a09=(-a09);
  if (res[0]!=0) res[0][10]=a09;
  a09=(a02/a01);
  a11=(a00+a09);
  a01=(a02/a01);
  a12=(a04*a01);
  a11=(a11-a12);
  a11=(-a11);
  if (res[0]!=0) res[0][11]=a11;
  a10=(a00-a10);
  a03=(a03*a10);
  a08=(a08+a03);
  if (res[0]!=0) res[0][12]=a08;
  a01=(a00-a01);
  a04=(a04*a01);
  a09=(a09+a04);
  if (res[0]!=0) res[0][13]=a09;
  a09=(a02/a05);
  a04=(a00+a09);
  a01=(a02/a05);
  a08=(a06*a01);
  a04=(a04-a08);
  a04=(-a04);
  if (res[0]!=0) res[0][14]=a04;
  a04=(a02/a05);
  a08=(a00+a04);
  a02=(a02/a05);
  a05=(a07*a02);
  a08=(a08-a05);
  a08=(-a08);
  if (res[0]!=0) res[0][15]=a08;
  a01=(a00-a01);
  a06=(a06*a01);
  a09=(a09+a06);
  if (res[0]!=0) res[0][16]=a09;
  a00=(a00-a02);
  a07=(a07*a00);
  a04=(a04+a07);
  if (res[0]!=0) res[0][17]=a04;
  a04=arg[0]? arg[0][0] : 0;
  a04=(-a04);
  if (res[0]!=0) res[0][18]=a04;
  a04=arg[0]? arg[0][1] : 0;
  a04=(-a04);
  if (res[0]!=0) res[0][19]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ceq1_v_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int ceq1_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ceq1_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    case 6: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq1_max_func:(i0[8],i1,i2,i3,i4,i5,i6)->(o0[9]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[5]? arg[5][0] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a1=(a1/a2);
  a1=exp(a1);
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a2=arg[4]? arg[4][0] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][4] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[0]? arg[0][6] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0]? arg[0][7] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_max_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_max_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq1_max_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq1_max_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq1_max_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int cineq1_max_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq1_max_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_max_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_max_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_max_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    case 6: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_max_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq1_min_func:(i0[8],i1,i2,i3,i4,i5,i6)->(o0[9]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[6]? arg[6][0] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a0=(a0/a1);
  a0=exp(a0);
  a1=arg[1]? arg[1][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a1=(a0-a1);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[4]? arg[4][0] : 0;
  a2=arg[0]? arg[0][1] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][2]=a2;
  a2=arg[0]? arg[0][2] : 0;
  a2=(a0-a2);
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[0]? arg[0][3] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][4]=a2;
  a2=arg[0]? arg[0][4] : 0;
  a2=(a0-a2);
  if (res[0]!=0) res[0][5]=a2;
  a2=arg[0]? arg[0][5] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][6]=a2;
  a2=arg[0]? arg[0][6] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0]? arg[0][7] : 0;
  a1=(a1-a0);
  if (res[0]!=0) res[0][8]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_min_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_min_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq1_min_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq1_min_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq1_min_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int cineq1_min_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq1_min_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_min_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_min_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_min_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    case 6: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_min_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq1_max_v_func:(i0[8],i1,i2,i3,i4,i5,i6)->(o0[9x15,9nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_max_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_max_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq1_max_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq1_max_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq1_max_v_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int cineq1_max_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq1_max_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_max_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_max_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_max_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    case 6: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_max_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq1_min_v_func:(i0[8],i1,i2,i3,i4,i5,i6)->(o0[9x15,9nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=-1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_min_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_min_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq1_min_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq1_min_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq1_min_v_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int cineq1_min_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq1_min_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_min_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_min_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_min_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    case 6: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_min_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
